<?php
function NameToChID($id)
{
    switch($id){
    case "Aatrox": return 266; break;
    case "Thresh": return 412; break;
    case "Tryndamere": return 23; break;
    case "Gragas": return 79; break;
    case "Cassiopeia": return 69; break;
    case "Aurelion Sol": return 136; break;
    case "Ryze": return 13; break;
    case "Poppy": return 78; break;
    case "Sion": return 14; break;
    case "Annie": return 1; break;
    case "Jhin": return 202; break;
    case "Karma": return 43; break;
    case "Nautilus": return 111; break;
    case "Kled": return 240; break;
    case "Lux": return 99; break;
    case "Ahri": return 103; break;
    case "Olaf": return 2; break;
    case "Viktor": return 112; break;
    case "Anivia": return 34; break;
    case "Singed": return 27; break;
    case "Garen": return 86; break;
    case "Lissandra": return 127; break;
    case "Maokai": return 57; break;
    case "Morgana": return 25; break;
    case "Evelynn": return 28; break;
    case "Fizz": return 105; break;
    case "Heimerdinger": return 74; break;
    case "Zed": return 238; break;
    case "Rumble": return 68; break;
    case "Mordekaiser": return 82; break;
    case "Sona": return 37; break;
    case "Kog'Maw": return 96; break;
    case "Katarina": return 55; break;
    case "Lulu": return 117; break;
    case "Ashe": return 22; break;
    case "Karthus": return 30; break;
    case "Alistar": return 12; break;
    case "Darius": return 122; break;
    case "Vayne": return 67; break;
    case "Varus": return 110; break;
    case "Udyr": return 77; break;
    case "Leona": return 89; break;
    case "Jayce": return 126; break;
    case "Syndra": return 134; break;
    case "Pantheon": return 80; break;
    case "Riven": return 92; break;
    case "Kha'Zix": return 121; break;
    case "Corki": return 42; break;
    case "Azir": return 268; break;
    case "Caitlyn": return 51; break;
    case "Nidalee": return 76; break;
    case "Kennen": return 85; break;
    case "Galio": return 3; break;
    case "Veigar": return 45; break;
    case "Bard": return 432; break;
    case "Gnar": return 150; break;
    case "Malzahar": return 90; break;
    case "Graves": return 104; break;
    case "Vi": return 254; break;
    case "Kayle": return 10; break;
    case "Irelia": return 39; break;
    case "Lee Sin": return 64; break;
    case "Illaoi": return 420; break;
    case "Elise": return 60; break;
    case "Volibear": return 106; break;
    case "Nunu": return 20; break;
    case "Twisted Fate": return 4; break;
    case 24: return "Jax"; break;
    case 102: return "Shyvana"; break;
    case 429: return "Kalista"; break;
    case 36: return "Dr. Mundo"; break;
    case 427: return "Ivern"; break;
    case 131: return "Diana"; break;
    case 223: return "Tahm Kench"; break;
    case 63: return "Brand"; break;
    case 113: return "Sejuani"; break;
    case 8: return "Vladimir"; break;
    case 154: return "Zac"; break;
    case 421: return "Rek'Sai"; break;
    case 133: return "Quinn"; break;
    case 84: return "Akali"; break;
    case 163: return "Taliyah"; break;
    case 18: return "Tristana"; break;
    case 120: return "Hecarim"; break;
    case 15: return "Sivir"; break;
    case 236: return "Lucian"; break;
    case 107: return "Rengar"; break;
    case 19: return "Warwick"; break;
    case 72: return "Skarner"; break;
    case 54: return "Malphite"; break;
    case 157: return "Yasuo"; break;
    case 101: return "Xerath"; break;
    case 17: return "Teemo"; break;
    case 75: return "Nasus"; break;
    case 58: return "Renekton"; break;
    case 119: return "Draven"; break;
    case 35: return "Shaco"; break;
    case 50: return "Swain"; break;
    case 91: return "Talon"; break;
    case 40: return "Janna"; break;
    case 115: return "Ziggs"; break;
    case 245: return "Ekko"; break;
    case 61: return "Orianna"; break;
    case 114: return "Fiora"; break;
    case 9: return "Fiddlesticks"; break;
    case 31: return "Cho'Gath"; break;
    case 33: return "Rammus"; break;
    case 7: return "LeBlanc"; break;
    case 16: return "Soraka"; break;
    case 26: return "Zilean"; break;
    case 56: return "Nocturne"; break;
    case 222: return "Jinx"; break;
    case 83: return "Yorick"; break;
    case 6: return "Urgot"; break;
    case 203: return "Kindred"; break;
    case 21: return "Miss Fortune"; break;
    case 62: return "Wukong"; break;
    case 53: return "Blitzcrank"; break;
    case 98: return "Shen"; break;
    case 201: return "Braum"; break;
    case 5: return "Xin Zhao"; break;
    case 29: return "Twitch"; break;
    case 11: return "Master Yi"; break;
    case 44: return "Taric"; break;
    case 32: return "Amumu"; break;
    case 41: return "Gangplank"; break;
    case 48: return "Trundle"; break;
    case 38: return "Kassadin"; break;
    case 161: return "Vel'Koz"; break;
    case 143: return "Zyra"; break;
    case 267: return "Nami"; break;
    case 59: return "Jarvan IV"; break;
    case 81: return "Ezreal"; break;
    default: return -1 break;
    }
}
?>